// Mocks generated by Mockito 5.0.3 from annotations
// in qr_generator/test/domain/usecases/get_seed_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:errors/src/failures.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:qr_generator/src/data/repositories/qr_generator_repository.dart'
    as _i3;
import 'package:qr_generator/src/domain/entities/seed.dart' as _i6;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [QrGeneratorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQrGeneratorRepository extends _i1.Mock
    implements _i3.QrGeneratorRepository {
  MockQrGeneratorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Seed>> getSeed() =>
      (super.noSuchMethod(Invocation.method(#getSeed, []),
              returnValue: Future.value(_FakeEither<_i5.Failure, _i6.Seed>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Seed>>);
}
