// Mocks generated by Mockito 5.0.3 from annotations
// in qr_generator/test/data/datasources/local_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:qr_generator/src/data/datasources/local_data_source.dart'
    as _i3;
import 'package:qr_generator/src/data/models/seed_model.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeSeedModel extends _i1.Fake implements _i2.SeedModel {}

/// A class which mocks [ILocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocalDataSource extends _i1.Mock implements _i3.ILocalDataSource {
  MockILocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SeedModel> getLocalGeneratedSeed() =>
      (super.noSuchMethod(Invocation.method(#getLocalGeneratedSeed, []),
              returnValue: Future.value(_FakeSeedModel()))
          as _i4.Future<_i2.SeedModel>);
}
